#!/usr/bin/env python3
"""Generate COMPANY_COVERAGE.md from companies.json (PRD §32).

    python scripts/company_coverage.py            # print
    python scripts/company_coverage.py --write    # write COMPANY_COVERAGE.md

The document is generated rather than hand-written so it cannot drift from the
registry, and so the definition of "supported" stays in one place.
"""

from __future__ import annotations

import argparse
import json
import sys
from collections import Counter
from datetime import UTC, datetime
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "src"))

from jobmonitor.discovery import RECOGNISED_UNSUPPORTED  # noqa: E402
from jobmonitor.models.company import (  # noqa: E402
    CompanyRegistry,
    Priority,
    SupportStatus,
    load_default_registry,
)

OUTPUT = REPO_ROOT / "COMPANY_COVERAGE.md"
SNAPSHOT = REPO_ROOT / "data" / "seed" / "discovery_snapshot.json"

PROVIDER_ENDPOINTS = {
    "greenhouse": "`GET boards-api.greenhouse.io/v1/boards/{token}/jobs`",
    "lever": "`GET api.lever.co/v0/postings/{site}`",
    "ashby": "`GET api.ashbyhq.com/posting-api/job-board/{board}`",
    "workday": "`POST {tenant}.wdN.myworkdayjobs.com/wday/cxs/.../jobs`",
    "smartrecruiters": "`GET api.smartrecruiters.com/v1/companies/{id}/postings`",
    "workable": "`GET apply.workable.com/api/v1/widget/accounts/{sub}`",
    "rippling": "`GET api.rippling.com/platform/api/ats/v1/board/{slug}/jobs`",
    "json_ld": "schema.org JobPosting JSON-LD embedded in a careers page",
    "simplify_fallback": "the Simplify community feed (secondary fallback only)",
}

DEFINITION = """\
## What the statuses mean

This project refuses to call a company "supported" on the strength of a slug that
looked plausible. Each status is a specific, checkable claim.

**`supported`** - all of these hold:

1. The company's `provider_config` came from **real evidence, never a guess**:
   either application URLs observed for that company in the seed repositories,
   or (for companies added later) the ATS its own careers page links to, with the
   board's ownership checked by where its apply URLs point. Each entry's notes
   say which.
2. Its provider adapter passes the shared Level-2 contract suite
   (`tests/scrapers/test_provider_contract.py`) against a fixture captured from
   that provider's real responses.
3. A **per-company** test (`tests/scrapers/test_registry_configs.py`) builds the
   adapter from this company's own config, checks the request it would issue goes
   to the right host and identifies this company, and replays the provider
   fixture through it to confirm valid jobs come out attributed to this company.
4. Nothing else in the registry shares its provider configuration.
5. The **live** source answered the last validation run with a conclusive result
   (`make validate-companies`, recorded in `data/validation.json`).

**`partial`** - pollable, but with a named caveat:

* *Second-hand source.* Read through the Simplify community feed because the
  employer exposes no first-party source a plain, unauthenticated request can
  read (token walls, bot protection, or no discoverable endpoint). This lags the
  employer's own board and only sees roles a contributor filed, so it can never
  be `supported`.
* *Degraded source.* The last live run could read the board, but not all of it
  (a page cap, or records that would not parse).

**`blocked`** - recorded but not polled: no first-party source is reachable
without getting past a login or a bot wall, and no secondary source exists.

**What a transient failure means:** nothing. A 429 or 5xx during validation is
*inconclusive*: the company keeps its status and no verdict is written, because
a rate limit says nothing about whether the configuration is right.
"""


def build(registry: CompanyRegistry) -> str:
    counts = registry.counts_by_status()
    providers = registry.counts_by_provider()
    pollable = registry.pollable()

    researched = 0
    configured = 0
    if SNAPSHOT.exists():
        snapshot = json.loads(SNAPSHOT.read_text(encoding="utf-8"))
        researched = int(snapshot.get("total_employers", 0))
        configured = sum(
            1 for row in snapshot.get("employers", {}).values() if row.get("supported")
        )

    validated = {c.last_validated for c in registry if c.last_validated} - {None}
    validation_line = (
        f"Last live validation: **{sorted(validated)[-1]}** (`make validate-companies`)"
        if validated
        else "Last live validation: **never run in this environment** - see `BLOCKERS.md` BLK-001."
    )

    lines: list[str] = [
        "# Company coverage",
        "",
        "<!-- GENERATED by scripts/company_coverage.py - do not edit by hand. -->",
        f"_Generated {datetime.now(UTC).date().isoformat()} from `companies.json`._",
        "",
        "## Summary",
        "",
        "```text",
        f"Employers discovered from the seed repositories : {researched}",
        f"  ...of which expose a configured ATS endpoint  : {configured}",
        f"Companies curated into the registry             : {len(registry)}",
        f"Companies monitored every poll (pollable)       : {len(pollable)}",
        "```",
        "",
        "| Status | Companies |",
        "| --- | --- |",
    ]
    for status in SupportStatus:
        if counts[status.value]:
            lines.append(f"| `{status.value}` | {counts[status.value]} |")
    lines += ["", validation_line, "", DEFINITION, "", "## Provider breakdown", ""]
    lines += ["| Provider | Companies | Endpoint |", "| --- | --- | --- |"]
    for provider, count in providers.items():
        lines.append(f"| `{provider}` | {count} | {PROVIDER_ENDPOINTS.get(provider, 'n/a')} |")

    ready = sorted(set(PROVIDER_ENDPOINTS) - set(providers) - {"json_ld", "simplify_fallback"})
    if ready:
        lines += [
            "",
            "Adapters implemented and tested but not yet used by any company, so adding "
            "one of those employers is a registry entry rather than code: "
            + ", ".join(f"`{name}`" for name in ready)
            + ".",
        ]

    lines += ["", "## Priority mix", "", "| Priority | Companies |", "| --- | --- |"]
    priorities = Counter(company.priority.value for company in registry)
    for priority in Priority:
        if priorities[priority.value]:
            lines.append(f"| `{priority.value}` | {priorities[priority.value]} |")

    industries = Counter(company.industry for company in registry)
    lines += [
        "",
        f"Spanning **{len(industries)} industries** - the registry deliberately reaches well "
        "beyond Big Tech (PRD §3): AI labs, quantitative trading, developer tools, "
        "databases, security, fintech, autonomy, aerospace, robotics and semiconductors.",
        "",
        "## Unsupported providers, and why",
        "",
        "Recognised during discovery but deliberately not adapted. Naming the reason is "
        "the point: it says what it would take, rather than lumping them under "
        '"unknown".',
        "",
        "| Provider | Reason |",
        "| --- | --- |",
    ]
    for provider, reason in sorted(RECOGNISED_UNSUPPORTED.items()):
        lines.append(f"| `{provider}` | {reason} |")

    lines += ["", "## Every monitored company", ""]
    for provider, count in providers.items():
        entries = sorted(registry.by_provider(provider), key=lambda c: c.company.casefold())
        lines += [
            f"### `{provider}` - {count}",
            "",
            "| Company | Industry | Priority | Status |",
            "| --- | --- | --- | --- |",
        ]
        for company in entries:
            lines.append(
                f"| {company.company} | {company.industry} | "
                f"`{company.priority.value}` | `{company.support_status.value}` |"
            )
        lines.append("")

    caveated = [c for c in registry if c.support_status is not SupportStatus.SUPPORTED]
    if caveated:
        lines += [
            "## Caveated entries in detail",
            "",
            "| Company | Provider | Status | Why |",
            "| --- | --- | --- | --- |",
        ]
        for company in sorted(caveated, key=lambda c: c.company.casefold()):
            note = company.notes.replace("|", "/").replace("\n", " ")
            lines.append(
                f"| {company.company} | `{company.provider}` | "
                f"`{company.support_status.value}` | {note} |"
            )
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help=f"write {OUTPUT.name}")
    args = parser.parse_args(argv)

    document = build(load_default_registry())
    if args.write:
        OUTPUT.write_text(document, encoding="utf-8")
        print(f"wrote {OUTPUT.relative_to(REPO_ROOT)} ({len(document.splitlines())} lines)")
    else:
        print(document)
    return 0


if __name__ == "__main__":
    sys.exit(main())
